### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by tomij2k** [crimera/twitter-apk#4]
I just want to ask which latest APK you guys are using? Cause mine (downloaded from here) keeps reproducing errors when patching. Also, if you have tips on which patches to include or exclude that would be a great help.

**Comment by crimera** [comment]
You can however use https://github.com/REAndroid/APKEditor to merge the .apkm file whoch are release from apkmirror. Then use the merged apk for patching.

**Comment by tomij2k** [comment]
Gotcha. Thanks!
