### ISSUE TITLE
(help noob) how to build apks?

### ISSUE THREAD

**Issue by MondayNitro** [crimera/twitter-apk#6]
i forked this repo and made changes to the default selected patches, but when i run github actions, it completes in 30s without any error and no apk shown in releases, please can we get a how-to guide, im sure a lot of people will find this useful!
thanks

**Comment by MondayNitro** [comment]
![Screenshot 2024-09-01 203235](https://github.com/user-attachments/assets/81575d0f-30b3-48b0-95bf-dba65c0cc353)
![Screenshot 2024-09-01 203329](https://github.com/user-attachments/assets/a190ca40-b380-4af0-90e5-c7e6bfb5aeb0)

**Comment by s1nnohlakes** [comment]
The script seems to check the latest version from this repo, hence why it probably doesn't work.

**Comment by crimera** [comment]
> The script seems to check the latest version from this repo, hence why it probably doesn't work.

True, you have to manually replace all instances of "crimera/twitter-apk" from the script to make it worm on your end.

**Comment by MondayNitro** [comment]
> > The script seems to check the latest version from this repo, hence why it probably doesn't work.
> 
> True, you have to manually replace all instances of "crimera/twitter-apk" from the script to make it worm on your end.

so i should replace crimera with my username or anything random?

**Comment by MondayNitro** [comment]
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}

for some reason it gives this error at the end, apk patching, output patched competes but due to token error, its not output to releases

**Comment by crimera** [comment]
You have to set GH_TOKEN to a valid github token that has release permissions to your github repo.

![Screenshot_20240908-075828_Brave - Nightly](https://github.com/user-attachments/assets/db7314cb-2b73-4729-9e41-3acd20abf1ee)

**Comment by MondayNitro** [comment]
thanks a lot crimera and s1nnohlakes, it does release the output apk now :)
